/* Auto-generated by tools/sync_symbols.py — do not edit.
 * Source: symbols.toml (Einhander)
 * Progressive symbols: discover → label → manipulate via PSX_FN_*.
 */
#pragma once

/* guessed: SYSTEM.CNF / EXE entry PC (probe seed) */
#define PSX_FN_BootEntry 0x800155FCu
#define func_800155FC BootEntry  /* alias */
